<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmailSMSTemplateSeeder extends Seeder {
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run() {
		DB::table('email_sms_templates')->insert([
			[
				"name" => "Transfer Money",
				"slug" => "TRANSFER_MONEY",
				"subject" => "Transfer Money - Laven Solutions",
				"email_body" => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Laven Solutions has successfully processed a transfer of {{amount}} to your account {{account_number}} from {{sender_account_number}} on {{dateTime}}.</div>\r\n</div>",
				"sms_body" => "Dear {{name}}, Laven Solutions has successfully processed a transfer of {{amount}} to your account {{account_number}} from {{sender_account_number}} on {{dateTime}}.",
				"notification_body" => "Dear {{name}}, Laven Solutions has successfully processed a transfer of {{amount}} to your account {{account_number}} from {{sender_account_number}} on {{dateTime}}.",
				"shortcode" => "{{name}} {{account_number}} {{amount}} {{sender}} {{sender_account_number}} {{balance}} {{dateTime}}",
				"email_status" => 0,
				"sms_status" => 0,
				"notification_status" => 0,
				"template_mode" => 0,
			],
			[
				"name" => "Deposit Money",
				"slug" => "DEPOSIT_MONEY",
				"subject" => "Deposit Money - Laven Solutions",
				"email_body" => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Laven Solutions has credited your account {{account_number}} with {{amount}} on {{dateTime}}.</div>\r\n</div>",
				"sms_body" => "Dear {{name}}, Laven Solutions has credited your account {{account_number}} with {{amount}} on {{dateTime}}.",
				"notification_body" => "Dear {{name}}, Laven Solutions has credited your account {{account_number}} with {{amount}} on {{dateTime}}.",
				"shortcode" => "{{name}} {{account_number}} {{amount}} {{dateTime}} {{balance}} {{depositMethod}}",
				"email_status" => 0,
				"sms_status" => 0,
				"notification_status" => 0,
				"template_mode" => 0,
			],
			[
				"name" => "Deposit Request Approved",
				"slug" => "DEPOSIT_REQUEST_APPROVED",
				"subject" => "Deposit Request Approved - Laven Solutions",
				"email_body" => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Laven Solutions has approved your deposit request. Your account {{account_number}} has been credited with {{amount}} on {{dateTime}}.</div>\r\n</div>",
				"sms_body" => "Dear {{name}}, Laven Solutions has approved your deposit request. Your account {{account_number}} has been credited with {{amount}} on {{dateTime}}.",
				"notification_body" => "Dear {{name}}, Laven Solutions has approved your deposit request. Your account {{account_number}} has been credited with {{amount}} on {{dateTime}}.",
				"shortcode" => "{{name}} {{account_number}} {{amount}} {{dateTime}} {{balance}} {{depositMethod}}",
				"email_status" => 0,
				"sms_status" => 0,
				"notification_status" => 0,
				"template_mode" => 0,
			],
			[
				"name" => "Loan Request Approved",
				"slug" => "LOAN_REQUEST_APPROVED",
				"subject" => "Loan Request Approved - Laven Solutions",
				"email_body" => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Laven Solutions has approved your loan request of {{amount}} on {{dateTime}}. Please contact us for disbursement details.</div>\r\n</div>",
				"sms_body" => "Dear {{name}}, Laven Solutions has approved your loan request of {{amount}} on {{dateTime}}. Please contact us for disbursement details.",
				"notification_body" => "Dear {{name}}, Laven Solutions has approved your loan request of {{amount}} on {{dateTime}}.",
				"shortcode" => "{{name}} {{amount}} {{dateTime}}",
				"email_status" => 0,
				"sms_status" => 0,
				"notification_status" => 0,
				"template_mode" => 0,
			],
			[
				"name" => "Withdraw Request Approved",
				"slug" => "WITHDRAW_REQUEST_APPROVED",
				"subject" => "Withdraw Request Approved - Laven Solutions",
				"email_body" => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Laven Solutions has approved your withdrawal request. Your account has been debited with {{amount}} on {{dateTime}}.</div>\r\n</div>",
				"sms_body" => "Dear {{name}}, Laven Solutions has approved your withdrawal request. Your account has been debited with {{amount}} on {{dateTime}}.",
				"notification_body" => "Dear {{name}}, Laven Solutions has approved your withdrawal request. Your account has been debited with {{amount}} on {{dateTime}}.",
				"shortcode" => "{{name}} {{account_number}} {{amount}} {{withdrawMethod}} {{balance}} {{dateTime}}",
				"email_status" => 0,
				"sms_status" => 0,
				"notification_status" => 0,
				"template_mode" => 0,
			],
			[
				"name" => "Deposit Request Rejected",
				"slug" => "DEPOSIT_REQUEST_REJECTED",
				"subject" => "Deposit Request Rejected - Laven Solutions",
				"email_body" => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Laven Solutions has rejected your deposit request of {{amount}}.</div>\r\n<div>&nbsp;</div>\r\n<div>Amount:&nbsp;{{amount}}</div>\r\n<div>Deposit Method: {{depositMethod}}</div>\r\n<div>Please contact us if you have any questions.</div>\r\n</div>",
				"sms_body" => "Dear {{name}}, Laven Solutions has rejected your deposit request of {{amount}}. Please contact us for more information.",
				"notification_body" => "Dear {{name}}, Laven Solutions has rejected your deposit request of {{amount}}.",
				"shortcode" => "{{name}}  {{account_number}} {{amount}} {{depositMethod}} {{balance}}",
				"email_status" => 0,
				"sms_status" => 0,
				"notification_status" => 0,
				"template_mode" => 0,
			],
			[
				"name" => "Loan Request Rejected",
				"slug" => "LOAN_REQUEST_REJECTED",
				"subject" => "Loan Request Rejected - Laven Solutions",
				"email_body" => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Laven Solutions has rejected your loan request of {{amount}} on {{dateTime}}. Please contact us for more information.</div>\r\n</div>",
				"sms_body" => "Dear {{name}}, Laven Solutions has rejected your loan request of {{amount}} on {{dateTime}}. Please contact us for more information.",
				"notification_body" => "Dear {{name}}, Laven Solutions has rejected your loan request of {{amount}} on {{dateTime}}.",
				"shortcode" => "{{name}} {{amount}} {{dateTime}}",
				"email_status" => 0,
				"sms_status" => 0,
				"notification_status" => 0,
				"template_mode" => 0,
			],
			[
				"name" => "Withdraw Request Rejected",
				"slug" => "WITHDRAW_REQUEST_REJECTED",
				"subject" => "Withdraw Request Rejected - Laven Solutions",
				"email_body" => "<div>\r\n<div>Dear {{name}}, Laven Solutions has rejected your withdrawal request. Your transferred amount of {{amount}} has been returned to your account.</div>\r\n</div>",
				"sms_body" => "Dear {{name}}, Laven Solutions has rejected your withdrawal request. Your amount of {{amount}} has been returned to your account.",
				"notification_body" => "Dear {{name}}, Laven Solutions has rejected your withdrawal request. Your amount of {{amount}} has been returned to your account.",
				"shortcode" => "{{name}} {{account_number}} {{amount}} {{withdrawMethod}} {{dateTime}} {{balance}}",
				"email_status" => 0,
				"sms_status" => 0,
				"notification_status" => 0,
				"template_mode" => 0,
			],
			[
				"name" => "Withdraw Money",
				"slug" => "WITHDRAW_MONEY",
				"subject" => "Withdraw Money - Laven Solutions",
				"email_body" => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Laven Solutions has debited your account {{account_number}} with {{amount}} on {{dateTime}}.</div>\r\n</div>",
				"sms_body" => "Dear {{name}}, Laven Solutions has debited your account {{account_number}} with {{amount}} on {{dateTime}}.",
				"notification_body" => "Dear {{name}}, Laven Solutions has debited your account {{account_number}} with {{amount}} on {{dateTime}}.",
				"shortcode" => "{{name}} {{account_number}} {{amount}} {{dateTime}} {{withdrawMethod}} {{balance}}",
				"email_status" => 0,
				"sms_status" => 0,
				"notification_status" => 0,
				"template_mode" => 0,
			],
			[
				"name" => "Member Request Accepted",
				"slug" => "MEMBER_REQUEST_ACCEPTED",
				"subject" => "Member Request Accepted - Laven Solutions",
				"email_body" => "<div>\r\n<div>Dear {{name}},</div>\r\n<div>Laven Solutions has accepted your membership request on {{dateTime}}. You can now login to your account using your email and password.</div>\r\n</div>",
				"sms_body" => "",
				"notification_body" => "",
				"shortcode" => "{{name}} {{member_no}} {{dateTime}}",
				"email_status" => 0,
				"sms_status" => 0,
				"notification_status" => 0,
				"template_mode" => 1,
			],
			[
                "name"                => "Loan Payment Received",
                "slug"                => "LOAN_PAYMENT_RECEIVED",
                "subject"             => "Loan Payment Received - Laven Solutions",
                "email_body"          => "<p>Dear <strong>{{name}}</strong>,</p> <p>Laven Solutions has successfully received your loan payment of <strong>{{amount}}</strong> on <strong>{{dateTime}}</strong>. Thank you for your payment.</p> <p><strong>Payment Details:</strong></p> <ul> <li><strong>Loan ID:</strong> {{loanID}}</li> <li><strong>Payment Amount:</strong> {{amount}}</li> <li><strong>Payment Date:</strong> {{dateTime}}</li> <li><strong>Next Due Date:</strong> {{nextDueDate}}</li></ul>",
                "sms_body"            => "Dear {{name}}, Laven Solutions has received your loan payment of {{amount}} on {{dateTime}}. Thank you for your payment.",
                "notification_body"   => "Dear {{name}}, Laven Solutions has received your loan payment of {{amount}} on {{dateTime}}. Thank you for your payment.",
                "shortcode"           => "{{name}} {{amount}} {{loanID}} {{nextDueDate}} {{dateTime}}",
                "email_status"        => 0,
                "sms_status"          => 0,
                "notification_status" => 0,
                "template_mode"       => 0,
            ],
			[
				"name"                => "Overdue Loan Payment",
				"slug"                => "OVERDUE_LOAN_PAYMENT",
				"subject"             => "Overdue Loan Payment Alert - Laven Solutions",
				"email_body"          => "<p>Dear <strong>{{name}}</strong>,</p> <p>Laven Solutions regrets to inform you that your loan account has entered default status due to non-payment. Your loan payment of <strong>{{dueAmount}}</strong> was due on <strong>{{dueDate}}</strong>, and despite our previous reminders, Laven Solutions has not received the payment. Immediate action is required to prevent further consequences, including additional fees or legal actions.</p> <p><strong>Loan Details:</strong></p> <ul> <li><strong>Loan ID:</strong> {{loanID}}</li> <li><strong>Default Amount:</strong> {{dueAmount}}</li> <li><strong>Number of Due:</strong> {{numberOfDue}}</li> <li><strong>Due Date:</strong> {{dueDate}}</li> </ul> <p>Laven Solutions urges you to make the payment immediately or contact us to discuss your options. Failure to resolve this matter may result in additional penalties or legal actions.</p>",
				"sms_body"            => "Dear {{name}}, Laven Solutions has noted that your loan account is in default due to non-payment of {{dueAmount}}. Please make the payment immediately to avoid further consequences. Loan ID: {{loanID}}. Due Date: {{dueDate}}.",
				"notification_body"   => "Dear {{name}}, Laven Solutions has noted that your loan account is in default due to non-payment of {{dueAmount}}. Loan ID: {{loanID}}. Due Date: {{dueDate}}.",
				"shortcode"           => "{{name}} {{dueAmount}} {{numberOfDue}} {{loanID}} {{dueDate}}",
				"email_status"        => 0,
				"sms_status"          => 0,
				"notification_status" => 0,
				"template_mode"       => 0,
			],
			[
				"name"                => "Upcoming Loan Payment Reminder",
				"slug"                => "UPCOMING_LOAN_PAYMENT_REMINDER",
				"subject"             => "Upcoming Loan Payment Reminder - Laven Solutions",
				"email_body"          => "<p>Dear <strong>{{name}}</strong>,</p> <p>Laven Solutions reminds you that your next loan payment of <strong>{{amount}}</strong> for Loan ID <strong>{{loanID}}</strong> is due on <strong>{{dueDate}}</strong>. Please ensure timely payment to avoid any penalties.</p> <p><strong>Payment Details:</strong></p> <ul> <li><strong>Loan ID:</strong> {{loanID}}</li> <li><strong>Payment Amount:</strong> {{amount}}</li> <li><strong>Due Date:</strong> {{dueDate}}</li></ul> <p>If you have any questions, please do not hesitate to contact Laven Solutions.</p>",
				"sms_body"            => "Dear {{name}}, Laven Solutions reminds you that your next loan payment of {{amount}} for Loan ID {{loanID}} is due on {{dueDate}}. Please make the payment on time to avoid penalties.",
				"notification_body"   => "Dear {{name}}, Laven Solutions reminds you that your next loan payment of {{amount}} for Loan ID {{loanID}} is due on {{dueDate}}. Please make the payment on time to avoid penalties.",
				"shortcode"           => "{{name}} {{amount}} {{loanID}} {{dueDate}}",
				"email_status"        => 0,
				"sms_status"          => 0,
				"notification_status" => 0,
				"template_mode"       => 0,
			],
		]);
	}
}