<?php

namespace App\Http\Controllers;

use App\Models\Loan;
use App\Models\LoanPayment;
use App\Models\Member;
use App\Models\Transaction;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class LoanOfficerController extends Controller
{
    /**
     * Create a new controller instance.
     */
    public function __construct()
    {
        date_default_timezone_set(get_option('timezone', 'Asia/Dhaka'));
    }

    /**
     * A loan officer is any non-customer staff member (admin, superadmin, or
     * a "user" with a role such as "Loan Officer" assigned to them).
     */
    protected function officerTypes()
    {
        return ['admin', 'superadmin', 'user'];
    }

    /**
     * Overview: every staff member, how many clients they have, how much
     * has been disbursed to those clients, and how much revenue (fees +
     * interest + penalties) those clients have generated for the company.
     */
    public function index()
    {
        $officers = User::whereIn('user_type', $this->officerTypes())
            ->orderBy('name', 'asc')
            ->get(['id', 'name', 'email', 'user_type']);

        // Clients per officer
        $clientCounts = Member::whereNotNull('loan_officer_id')
            ->select('loan_officer_id', DB::raw('count(*) as cnt'))
            ->groupBy('loan_officer_id')
            ->pluck('cnt', 'loan_officer_id');

        // Money disbursed to each officer's clients (released loans only)
        $disbursed = Loan::join('members', 'members.id', '=', 'loans.borrower_id')
            ->whereNotNull('members.loan_officer_id')
            ->whereNotNull('loans.release_date')
            ->select('members.loan_officer_id', DB::raw('sum(loans.applied_amount) as total'))
            ->groupBy('members.loan_officer_id')
            ->pluck('total', 'loan_officer_id');

        // Application + processing fee revenue generated by each officer's clients
        $fees = Transaction::join('members', 'members.id', '=', 'transactions.member_id')
            ->whereNotNull('members.loan_officer_id')
            ->whereIn('transactions.type', ['loan_application_fee', 'loan_processing_fee'])
            ->where('transactions.status', 2)
            ->select('members.loan_officer_id', DB::raw('sum(transactions.amount) as total'))
            ->groupBy('members.loan_officer_id')
            ->pluck('total', 'loan_officer_id');

        // Interest + late payment penalty revenue collected from each officer's clients
        $interest = LoanPayment::join('members', 'members.id', '=', 'loan_payments.member_id')
            ->whereNotNull('members.loan_officer_id')
            ->select('members.loan_officer_id', DB::raw('sum(loan_payments.interest + loan_payments.late_penalties) as total'))
            ->groupBy('members.loan_officer_id')
            ->pluck('total', 'loan_officer_id');

        $data = [];
        foreach ($officers as $officer) {
            $officerFees     = (float) ($fees[$officer->id] ?? 0);
            $officerInterest = (float) ($interest[$officer->id] ?? 0);

            $data[] = [
                'officer'    => $officer,
                'clients'    => (int) ($clientCounts[$officer->id] ?? 0),
                'disbursed'  => (float) ($disbursed[$officer->id] ?? 0),
                'fees'       => $officerFees,
                'interest'   => $officerInterest,
                'profit'     => $officerFees + $officerInterest,
            ];
        }

        // Highest performing officers first
        usort($data, fn($a, $b) => $b['profit'] <=> $a['profit']);

        return view('backend.loan_officer.index', [
            'rows'  => $data,
            'totals' => [
                'clients'   => array_sum(array_column($data, 'clients')),
                'disbursed' => array_sum(array_column($data, 'disbursed')),
                'fees'      => array_sum(array_column($data, 'fees')),
                'interest'  => array_sum(array_column($data, 'interest')),
                'profit'    => array_sum(array_column($data, 'profit')),
            ],
        ]);
    }

    /**
     * Drill-down: every client attached to a single loan officer, and what
     * each of them has cost/earned the company.
     */
    public function show($id)
    {
        $officer = User::whereIn('user_type', $this->officerTypes())->findOrFail($id);

        $clients = Member::withoutGlobalScopes(['status'])
            ->where('loan_officer_id', $officer->id)
            ->with(['loans' => function ($q) {
                $q->select('id', 'borrower_id', 'applied_amount', 'total_payable', 'total_paid', 'release_date', 'status');
            }])
            ->orderBy('first_name', 'asc')
            ->get();

        $memberIds = $clients->pluck('id');

        $feesByMember = Transaction::whereIn('member_id', $memberIds)
            ->whereIn('type', ['loan_application_fee', 'loan_processing_fee'])
            ->where('status', 2)
            ->select('member_id', DB::raw('sum(amount) as total'))
            ->groupBy('member_id')
            ->pluck('total', 'member_id');

        $interestByMember = LoanPayment::whereIn('member_id', $memberIds)
            ->select('member_id', DB::raw('sum(interest + late_penalties) as total'))
            ->groupBy('member_id')
            ->pluck('total', 'member_id');

        $rows = [];
        foreach ($clients as $client) {
            $disbursed = $client->loans->whereNotNull('release_date')->sum('applied_amount');
            $fees      = (float) ($feesByMember[$client->id] ?? 0);
            $interest  = (float) ($interestByMember[$client->id] ?? 0);

            $rows[] = [
                'member'    => $client,
                'loans'     => $client->loans->count(),
                'disbursed' => (float) $disbursed,
                'fees'      => $fees,
                'interest'  => $interest,
                'profit'    => $fees + $interest,
            ];
        }

        return view('backend.loan_officer.show', [
            'officer' => $officer,
            'rows'    => $rows,
            'totals'  => [
                'loans'     => array_sum(array_column($rows, 'loans')),
                'disbursed' => array_sum(array_column($rows, 'disbursed')),
                'fees'      => array_sum(array_column($rows, 'fees')),
                'interest'  => array_sum(array_column($rows, 'interest')),
                'profit'    => array_sum(array_column($rows, 'profit')),
            ],
        ]);
    }
}


